name: HeadNamer
main: com.github.devilquak.HeadNamer
version: 1.2
api-version: 1.16
description: Rename a player-head item, painlessly simply and without hassle.
author: devilquak, dYens

commands:
   hname:
      description: Rename a player head in your hand.
      usage: ยง7Usa ยงb/hname [nombre]
      aliases: hn
      permission: headnamer.name
      permission-message: ยง7No tienes permiso para hacer eso.
permissions:
   headnamer.*:
      description: Allows usage of every Head Namer feature.
      children:
         headnamer.name: true
         headnamer.spawnnewitem: true
   headnamer.name:
      description: Allows the holder to rename a player head in their hand.
      default: op
   headnamer.spawnnewitem:
      description: Allows the holder to spawn a new named player-head if they are not holding one already.
      default: op